### PR TITLE
Plat 83

### PR DESCRIPTION
**Pull request by elisabeth-sorrell**
Database: database image based off of percona-xtradb-cluster, a mysql database that handles clustering through an external discovery service called etcd. etcd is the chosen discovery service because it is the only one that percona-xtradb supports so far. 

docker-compose.swarm.yml: deploys a db cluster, sonar, and etcd

docker-compose.yml: (meant for local docker-compose) deploys a db cluster with size=1 and sonar

docker-compose.jenkins-sonar.yml: (meant for local docker-compose) deploys a db cluster with size=1, sonar, jenkins, and sonar-jenkins config containers.

### CODE REVIEW

**Comment by abhijitvk** [comment]
@elisabeth-sorrell : Is this still a valid PR to be merged? @jasonluck

**Comment by elisabeth-sorrell** [comment]
@abhijitvk: Yes, it needs to be reviewed and merged. It also looks like development needs to be merged into this as well because this PR has been around for a while. @jasonluck I'm going to merge development into this branch and repush.

**Comment by elisabeth-sorrell** [comment]
@abhijitvk development has been merged. @jasonluck

**Comment by abhijitvk** [comment]
@elisabeth-sorrell : Please confirm if this PR can be closed without the merge now?

**Comment by abhijitvk** [comment]
Closing the PR, will reopen another one if needed.

**Pull request closed without merging**
